version: '3.0'
services:
  php:
    build:
      args:
        - user=ndk
        - uid=1000
      context: .
      dockerfile: Dockerfile-php
    image: php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - laravel-net
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      # - ./source:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - 8000:80
    networks:
      - laravel-net 
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    networks:
      - laravel-net
networks:
  laravel-net:
    driver: bridge
   